[package]
name = "rust-example-api-server"
version = "0.0.1"
authors = ["Kohei Asai <yo@kohei.dev>"]
edition = "2018"

[dependencies]
clap = "3.0.0-beta.2"
rocket = "^0.4.5"
rocket_contrib = "^0.4.5"
serde = { version = "^1.0.117", features = ["derive"] }
serde_json = "^1.0.59"
